# Generated by Django 6.1 on 2026-08-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
